{{config(materialized='view')}}

SELECT * FROM (
 SELECT O_ORDERDATE AS ORDER_DATE, 
SUM(O_TOTALPRICE) OVER(ORDER BY O_ORDERDATE) AS CUMULTV_TOTAL_PRICE 
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS
) GROUP BY 1,2
ORDER BY 1