{{ config(materialized='table') }}

SELECT 
C_CUSTKEY,
C_NAME,
SUM(O_TOTALPRICE)
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER C
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS O
ON C.C_CUSTKEY = O.O_CUSTKEY
GROUP BY 1,2