{{ config(materialized = 'table') }}

SELECT 
C_CUSTKEY,
C_NAME,
SUM(O_TOTALPRICE)
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER CUST
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS ORD
ON CUST.C_CUSTKEY = ORD.O_CUSTKEY
GROUP BY 1,2